name: Release Extension

on:
  workflow_dispatch:
    description: "Chrome拡張機能をリリースするワークフローです"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update manifest version
        run: |
          TAG="${{ steps.tag.outputs.new_tag }}"
          CLEANED_TAG="${TAG#v}"
          jq --arg v "$CLEANED_TAG" '.version = $v' extension/manifest.json > extension/manifest.tmp
          mv extension/manifest.tmp extension/manifest.json
      - name: Commit updated manifest
        run: |
          git add extension/manifest.json
          git commit -m "chore: manifest.json のバージョンを更新"
          git push
      - name: Package extension
        run: |
          cd extension
          zip -r ../extension.zip .
          cd .. # Return to repository root for following steps
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: ${{ steps.tag.outputs.new_tag }}
          generate_release_notes: true
          files: extension.zip
